title: Welcome to HyprBlue
properties:
  mode: "run-on-change"
screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to HyprBlue"
      description: |
        This is the Finalization of the Setup of HyprBlue.
  check-system-flathub:
    source: yafti.screen.consent
    values:
      title: Missing Flathub Repository (System)
      condition:
        run: flatpak remotes --system --columns=name | grep flathub | wc -l | grep '^0$'
      description: |
        We have detected that you don't have Flathub's repository on your system. We will now add that repository to your system-wide list.
      actions:
        - run: flatpak remote-add --if-not-exists --system flathub https://flathub.org/repo/flathub.flatpakrepo
  check-user-flathub:
    source: yafti.screen.consent
    values:
      title: Missing Flathub Repository (User)
      condition:
        run: flatpak remotes --user --columns=name | grep flathub | wc -l | grep '^0$'
      description: |
        We have detected that you don't have Flathub's repository on your current user account. We will now add that repository to your account.
      actions:
        - run: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      description: |
        Thanks for trying uBlue, we hope you enjoy it!
