name: hyprblue-framework
description: This is the Framework varient of HyprBlue
base-image: ghcr.io/ublue-os/base-main
image-version: latest

modules:
  - type: akmods
    base: extra
    install:
      - framework-laptop
  
  - from-file: base-packages.yml
  - from-file: services.yml
  - from-file: files.yml
  - type: signing